### PR TITLE
Try osx-arm64 migration with f2py hack.

### PR DESCRIPTION
**Pull request by erykoff**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by erykoff** [comment]
I got it past the f2py part, and now it's failing downstream of that.  @rhiannonlynne any ideas?

**Comment by rhiannonlynne** [comment]
Wow, that command line at (330 to 337 or so, depending on the particular build) in the error messages is bonkers. 
Is there an environment variable that got mangled somewhere, having that many placehold values, or is that actually correct? 
And I don't know why the `fdebug_prefix_map` is repeated in the command. 
`error: Command "gfortran -I../build -O3 -fPIC -std=f95 -fall-intrinsics -cpp -fPIC -march=armv8.3-a -ftree-vectorize -fPIC -fno-stack-protector -O2 -pipe -isystem /Users/runner/miniforge3/conda-bld/openorb_1675542164449/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/include -fdebug-prefix-map=/Users/runner/miniforge3/conda-bld/openorb_1675542164449/work=/usr/local/src/conda/openorb-1.0.1.20191029 -fdebug-prefix-map=/Users/runner/miniforge3/conda-bld/openorb_1675542164449/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p=/usr/local/src/conda-prefix -O3 -funroll-loops -I./_pyoorb_build/src.macosx-10.9-x86_64-3.11/_pyoorb_build/src.macosx-10.9-x86_64-3.11 -I/Users/runner/miniforge3/conda-bld/openorb_1675542164449/_build_env/venv/lib/python3.11/site-packages/numpy/core/include -I/Users/runner/miniforge3/conda-bld/openorb_1675542164449/_build_env/venv/build/include -I/Users/runner/miniforge3/conda-bld/openorb_1675542164449/_build_env/include/python3.11 -c -c _pyoorb_build/src.macosx-10.9-x86_64-3.11/pyoorb-f2pywrappers2.f90 -o ./_pyoorb_build/_pyoorb_build/src.macosx-10.9-x86_64-3.11/pyoorb-f2pywrappers2.o" failed with exit status 1`


I also am having some trouble finding where the `fdebug_prefix_map` flag is set .. I can't find it in any of the files that oorb comes with or should create to build the package.

**Comment by erykoff** [comment]
The placeholder stuttering is part of the design to make sure that all the internal paths are 256 characters and therefore can be patched cleanly later in the installation process.  But googling a bit further I found this https://github.com/numpy/numpy/issues/5876#issuecomment-151646875 which is old, but this error seems to be related to some bad code emitted by `f2py`?  Why it works on native and not cross is another mystery.

I'm having trouble replicating locally; my old x86 laptop something is all messed up; and testing cross compiling on my new laptop doesn't quite work to uncover the same sorts of bugs that happen on native x86.

**Comment by erykoff** [comment]
That seems to have done it.  I will have to dig into why the flags aren't working as intended within f2py.  And this is not beautiful, but will get the job done until we get the fixes merged upstream.

**Comment by rhiannonlynne** [comment]
Thanks so much, Eli! 
Can I ask one other question -- the bot picks the various versions of numpy, but why isn't there a numpy 1.24 version? Or is that not needed?

**Comment by erykoff** [comment]
So conda-forge by default builds with the lowest version of numpy that is compatible with that version of python, and then at runtime makes sure that you get a compatible version of that or later with the magic `{{ pin_compatible('numpy') }}` which I notice is not here; I will fix that on this PR.  In pip-land there's a package called `oldest-supported-numpy` which does the same thing.  (https://github.com/scipy/oldest-supported-numpy/blob/main/setup.cfg).  It's kind of a mess, but these tools are designed to work around that mess.

**Comment by rhiannonlynne** [comment]
Great - thanks a lot!

**Review by rhiannonlynne — APPROVED** [review]

**Comment by erykoff** [comment]
Great!  I don't know if you are waiting for somebody else to weigh in; if not, then it's up to you to hit that green merge button.  Thanks!

**Comment by erykoff** [comment]
Actually, there's one more thing I want to try...

**Comment by erykoff** [comment]
Please hold off on merging this, I think it's building but wrong.

**Comment by erykoff** [comment]
Well, this is not good.  Due to the hardwiring of the gfortran executable, it was actually not building the arm64 version.  I was able to patch the configure script to do the right thing (not pushed), and then got this error:
```
Undefined symbols for architecture arm64:
  "_logq", referenced from:
      ___random_MOD_randomgaussian_single_r16 in liboorb.a(random.o)
  "_powq", referenced from:
      ___random_MOD_randomgaussian_single_r16 in liboorb.a(random.o)
  "_sqrtq", referenced from:
      ___random_MOD_randomgaussian_single_r16 in liboorb.a(random.o)
ld: symbol(s) not found for architecture arm64
```
And after figuring out that fortran isn't case sensitive and symbols keep getting mangled, and then doing the right google, I realized that `_logq` is referring to quad-precision `LOG(REAL*16)`.  And arm64 does _not_ support quad precision math.

So ... does this code require quad-precision floats?

**Comment by rhiannonlynne** [comment]
Argh. I was hoping this had been resolved, given later comments in this (https://github.com/oorb/oorb/issues/146) PR on oorb (but yes, it does require REAL(*16)).

**Comment by rhiannonlynne** [comment]
Thanks for making the connection between these things. The error messages you describe are familiar, but we hadn't managed to do the right google. https://github.com/oorb/oorb/issues/155

**Comment by erykoff** [comment]
So this does seem fixable (that REAL*16 isn't strictly necessary), but this migration won't work until the fix is done upstream.  I'll push my changes which shows the actual fail to compile.

**Comment by erykoff** [comment]
Oh, the changes I pushed will die before the quad precision error because the makefile linker isn't using the correct flags/paths.  I don't have time right now to do that surgery.  But I wanted to flag this for when we can come back to it.

**Comment by erykoff** [comment]
@rhiannonlynne @conda-forge/openorb This is now working on osx-arm64 with the latest conda forge version of gfortran12!

**Comment by rhiannonlynne** [comment]
Thank you so much @erykoff !  That was a ton of work and I appreciate it.

**Pull request merged**
